name: Build and Push Docker image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  

    - name: Build and push Docker client image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:client"
        file: ./Dockerfile
        push: true
        tags: ghcr.io/nttyssen/nptestbenchclient:latest 
    
    - name: Build and push Docker server image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:server"
        file: ./Dockerfile
        push: true
        tags: ghcr.io/ntthyssen/nptestbenchclient:latest
      