name: Build and Push Docker image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}  # This uses the GitHub token for automation

    - name: Build and push Docker client image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./client/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/NPTestBenchClient:latest
    
    - name: Build and push Docker server image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./server/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/NPTestBenchServer:latest
      